### ISSUE TITLE
Build LIT Animated Carousel

### ISSUE THREAD

**Issue by bpod** [befreestudios-io/web-components-sandbox#18]
Build and implement a LIT Carousel

Example: https://lit.dev/tutorials/carousel/

**Comment by AaryanSingh0017** [comment]
Hey can you assign me this and in which file do I have to make changes.

**Comment by bpod** [comment]
Assigned! You can create a new directory for the carousel files in `components/LIT`

Something like `components/LIT/Carousel` would be good. Thanks and good luck!
